version: '3'
services:
  test-web-site:
    image: "gridlastic/docker-hello-world"
    ports:
      - "8001:80"

  gridc-config-tunnels:
    image: gridlastic/docker-gridc
    ports:
      - "3000:3000"
    volumes:
      - ./custom-config-template.cfg:/home/gridc/config-template.cfg
    environment:
      GRIDC_ENDPOINT_SUBDOMAIN: ${GRIDC_ENDPOINT_SUBDOMAIN}
      GRIDC_USERNAME: ${GRIDC_USERNAME}
      GRIDC_ACCESS_KEY: ${GRIDC_ACCESS_KEY}
      GRIDC_HUB: 3000
      GRIDC_CONFIG_SUBDOMAIN_UUID_PREFIX: ${GRIDC_CONFIG_SUBDOMAIN_UUID_PREFIX}
      GRIDC_START_CONFIG_TUNNELS: all

      


  test-web-site-1:
    image: "gridlastic/docker-hello-world"

  test-web-site-2:
    image: "gridlastic/docker-hello-world"
 
    
  gridc-tunnel-1:
    image: gridlastic/docker-gridc
    environment:
      GRIDC_ENDPOINT_SUBDOMAIN: ${GRIDC_ENDPOINT_SUBDOMAIN}
      GRIDC_USERNAME: ${GRIDC_USERNAME}
      GRIDC_ACCESS_KEY: ${GRIDC_ACCESS_KEY}
      GRIDC_PROTOCOL: https
      GRIDC_SUBDOMAIN: ${GRIDC_CONFIG_SUBDOMAIN_UUID_PREFIX}-test-web-site-1
      GRIDC_ADDR_DOMAIN: test-web-site-1
      GRIDC_ADDR_PORT: 80
      
  gridc-tunnel-2:
    image: gridlastic/docker-gridc
    environment:
      GRIDC_ENDPOINT_SUBDOMAIN: ${GRIDC_ENDPOINT_SUBDOMAIN}
      GRIDC_USERNAME: ${GRIDC_USERNAME}
      GRIDC_ACCESS_KEY: ${GRIDC_ACCESS_KEY}
      GRIDC_PROTOCOL: https
      GRIDC_SUBDOMAIN: ${GRIDC_CONFIG_SUBDOMAIN_UUID_PREFIX}-test-web-site-2
      GRIDC_ADDR_DOMAIN: test-web-site-2
      GRIDC_ADDR_PORT: 80